version: "3.7"
services:
  create-microservice-map:
    image: "ianitrix/create-microservice-map:latest"
    hostname: create-microservice-map
    environment:
      - NEO4J_URL=http://neo4j:7474
      - APIM_USER=admin
      - APIM_PASS=admin
      - APIM_URL=http://management_api:8083
      - AKHQ_URL=http://akhq:8080
      - AKHQ_USER=admin
      - AKHQ_PASSWORD=admin
      - AKHQ_CLUSTER=docker-kafka-server
      - AKHQ_CONNECT_CLUSTER=default
    restart: on-failure
    depends_on:
      - neo4j
    ports:
      - 8081:80
    networks:
      - net

  neo4j:
    image: "neo4j:4.1.1"
    hostname: neo4j
    restart: on-failure
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - net
    healthcheck:
      test: test `wget --spider -S http://localhost:7474 2>&1 | grep "HTTP/" |  awk '{print $$2}'` = 200
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s

networks:
  net:
    external:
      name: net
