version: "3.7"
services:
  create-microservice-map:
    image: "ianitrix/create-microservice-map:latest"
    hostname: create-microservice-map
    environment:
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_DB=test
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=passwordSecure
      - GRAVITEE_USER=admin
      - GRAVITEE_PASS=admin
      - GRAVITEE1_URL=http://management_api:8083
      - AKHQ_URL=http://akhq:8080
      - AKHQ_USER=admin
      - AKHQ_PASSWORD=admin
      - AKHQ_CLUSTER=docker-kafka-server
      - AKHQ_CONNECT_CLUSTER=default
      - MONGODB_ATLAS_URL=https://cloud.mongodb.com
      - MONGODB_ATLAS_USER=xxx
      - MONGODB_ATLAS_PASS=xxx
      - MONGODB_ATLAS_PROJECT_ID=xxx
    restart: on-failure
    depends_on:
      - neo4j
    ports:
      - 8081:80
    networks:
      - net

  neo4j:
    image: "neo4j:4.1.1"
    hostname: neo4j
    restart: on-failure
    environment:
     # - NEO4J_AUTH=none
      - NEO4J_AUTH=neo4j/passwordSecure
      - NEO4J_dbms_default__database=test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - net
    healthcheck:
      test: test `wget --spider -S http://localhost:7474 2>&1 | grep "HTTP/" |  awk '{print $$2}'` = 200
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s

networks:
  net:
    external:
      name: net
