# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
     
   
    # Push docker image (master=latest)
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2.10.0
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: ianitrix/create-microservice-map
         tag_with_ref: true
 
   
    # Create GitHub release
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ github.ref }}
         release_name: v${{ steps.versionName.outputs.versionName }}
         draft: true
         prerelease: true
    
